### ISSUE TITLE
ValueError: Port could not be cast to integer value as 'm64w9xQRwrXqdV'

### ISSUE THREAD

**Issue by eduzen** [jacobian/dj-database-url#133]
Hi, maybe someone can give me some hint here. I'm pretty lost.  I used the database url with `pgcli` and with `psql` and it works fine. But whenever I want to use it inside of my settings, it crashes. 

I tried to find another issue and I couldn't find it. 😭 

Maybe if there is a real bug I also can help to fix it.

Thanks!
```
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'm64w9xQRwrXqdV'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/local/lib/python3.8/site-packages/configurations/importer.py", line 182, in load_module
    reraise(err, "Couldn't setup configuration '{0}'".format(cls_path))
  File "/usr/local/lib/python3.8/site-packages/configurations/importer.py", line 164, in load_module
    cls.setup()
  File "/usr/local/lib/python3.8/site-packages/configurations/base.py", line 127, in setup
    setup_value(cls, name, value)
  File "/usr/local/lib/python3.8/site-packages/configurations/values.py", line 15, in setup_value
    actual_value = value.setup(name)
  File "/usr/local/lib/python3.8/site-packages/configurations/values.py", line 103, in setup
    value = self.to_python(os.environ[full_environ_name])
  File "/usr/local/lib/python3.8/site-packages/configurations/values.py", line 447, in to_python
    value = super(DictBackendMixin, self).to_python(value)
  File "/usr/local/lib/python3.8/site-packages/configurations/values.py", line 174, in to_python
    raise ValueError(self.message.format(value))
ValueError: Couldn't setup configuration 'website.settings.Dev':  Cannot interpret database URL value 'postgres://*****:*****@eduzen.czgr9lcuj5tv.us-east-1.rds.amazonaws.com:5432/'
```

**Comment by arnav13081994** [comment]
@eduzen Can you write the exact url you used?

**Comment by eduzen** [comment]
Thanks @arnav13081994, I think you are right about the special characters! I would change them or quote them!
